services:
  fa-fashboard:
    build: .
    image: fa_traceability
    container_name: fa_traceability
    restart: always
    environment:
      - FLASK_ENV=production
    networks:
      - manufacturing_network
networks:
  manufacturing_network:
    external: true